### ISSUE TITLE
Support for python3

### ISSUE THREAD

**Issue by Delta1977** [mapillary/mapillary_tools#374] opened 2020-07-08 12:48 UTC
Python 2.7 reached the end of its life on January 1st, 2020 . 
When would mapillary_tool support python3  ?

**Comment by fgouget** [comment] 2020-08-09 10:48
The Travis Continuous Integration on github also requires Python 3 which means every pull request now gets an error:

| pip 20.1.1 from /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip (python 3.6)
[...]
| ERROR: Package 'mapillary-tools' requires a different Python: 3.6.7 not in '>=2.7.0,<3.0.0'
| The command "eval pip install -r requirements.txt " failed. Retrying, 2 of 3.

My understanding is that pip is a Python 3 shim that just says Python 2 is no longer supported.
This does make continuous integration pretty pointless (and gives the impression mapillary_tools is not maintained anymore :-( ).

**Comment by paulb20** [comment] 2020-08-27 19:14
Adding a voice here - as my Ubuntu has updated to 20.04, Python 3 is the only python supported and therefore the mapillary tools cannot be used without seriously messing up conformant python 3 applications.

**Comment by arne182** [comment] 2020-09-16 09:46
Tried to get the dependencies for 2.7 together and it was a mess. What is needed to get this to be python 3 compatible?

**Comment by Nick-Tallguy** [comment] 2020-11-01 21:14
Installing **python-dev** before attempting to install worked for me - see issue https://github.com/mapillary/mapillary_tools/issues/354 (Thanks to @ltog for the clue here) Ubuntu 20.04 server;

      $ sudo apt install python-dev  
cd to directory in home where installing virtualenv and mapillary, then  

      $ virtualenv -p /bin/python2 venv  
      $ source venv/bin/activate
      $ pip install git+https://github.com/mapillary/Piexif  
      $ pip install --upgrade git+https://github.com/mapillary/mapillary_tools

**Comment by duckonomy** [comment] 2021-01-13 16:27
Any updates on this? 
Is there work going into #377?
I'd really like to help porting if help is needed.

**Comment by ptpt** [comment] 2021-02-17 13:09
Hi all,

We appreciate all the feedback. I will be working on porting the code to Python3, and release 0.6.0-beta around next week. Would be great if you can help test it out!

The plan:
1. port to Python3 (>=3.6)
2. make it easy to install via pip

cc @eneerhut 

Thanks!

**Comment by scaidermern** [comment] 2021-02-19 06:56
This ticket is a duplicate of #227.

**Comment by ptpt** [comment] 2021-02-23 22:51
Hi all,

The Python3 port is close to be done. I tested the basic process and upload and it works great. It would be great to have your help to get more tested. The installation is documented here: https://github.com/mapillary/mapillary_tools/tree/fix-upload#package-installation-python3

I will close this issue and track the progress in #227.

Thanks!

**Closed by ptpt** 2021-02-23 22:51 UTC
