### ISSUE TITLE
Authentication failed when user name contains non-ASCII charactors

### ISSUE THREAD

**Issue by kudarisenmon** [mapillary/mapillary_tools#281] opened 2018-08-26 11:03 UTC
### Basic information
* Release version: `0.1.5`
* System: `Linux`

### Steps to reproduce behavior

 1.  My user name contains Japanese (non-ASCII) charactors
 2.  Run "mapillary_tools authenticate --advanced"
 3. Error with "Authentication failed for user name 下り専門, please try again."

### Expected behavior

Even if the user name contains non-ASCII (Japanese) characters, it should be able to authenticate

### Actual behavior

Error with "Authentication failed for user name 下り専門, please try again."

**Comment by jernejaMislej** [comment] 2018-08-26 21:43
hi thank you for trying mapillary_tools and opening an issue. 
as far as i know we did not consider non-ASCII characters in usernames, I will have a look and let you know asp

**Comment by jernejaMislej** [comment] 2018-09-12 07:08
hi, sorry for getting back late.
can you please check what username is shown when you log into the mapillary web app [here](https://www.mapillary.com/app/)?
![image](https://user-images.githubusercontent.com/19649323/45407937-2434dc00-b66b-11e8-83be-7a0bf328f07a.png)


it could be that japanese characters are translated into different characters in our system.
let me know if you see that your username in the web actually does contain japanese characters, if not please use the username displayed in the web app when using the tools and close this issue

**Comment by kudarisenmon** [comment] 2018-09-13 10:43
Hi, The spelling of my username is 下り専門
![2018-09-13 19 41 16](https://user-images.githubusercontent.com/2560699/45483760-db754400-b78c-11e8-89bf-3d1c7479ab48.png)
Thank you.

**Comment by Kaldea** [comment] 2018-09-13 11:42
Hi @kudarisenmon I'm going to do what I can to help you from here. I have no other examples of non-ascii character usernames working in our system so I'm looking into what/how has happened to allow this for now. For us to fix your original issue, can you please go in and try to change (even if temporarily) your username in your dashboard settings? Please let me know if the issue is resolved with this or not. I will also look into what our stance is on non-ascii character usernames moving forward. Thanks!

**Comment by kudarisenmon** [comment] 2018-09-14 10:16
Hi, @jernejaMislej , @Kaldea I have debugged and send pull request.
Please review.
Thank you.

**Comment by jernejaMislej** [comment] 2018-09-17 22:52
hi
thank you for contributing. i merged your fix to the branch for next release v0.2.0

**Closed by jernejaMislej** 2018-09-17 22:52 UTC
